//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język:.
        /// </summary>
        public static string AppLang {
            get {
                return ResourceManager.GetString("AppLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komenda:.
        /// </summary>
        public static string ClientCommand {
            get {
                return ResourceManager.GetString("ClientCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polaczono z klientem:.
        /// </summary>
        public static string ClientConnected {
            get {
                return ResourceManager.GetString("ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozlaczono klienta.
        /// </summary>
        public static string ClientDisconnected {
            get {
                return ResourceManager.GetString("ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIEPRAWIDLOWY ODCZYT Z PLIKU config.ini.
        /// </summary>
        public static string ConfigFileError {
            get {
                return ResourceManager.GetString("ConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane do polaczenia:.
        /// </summary>
        public static string ConnectionParams {
            get {
                return ResourceManager.GetString("ConnectionParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        public static string ConnectionPassword {
            get {
                return ResourceManager.GetString("ConnectionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string ConnectionPort {
            get {
                return ResourceManager.GetString("ConnectionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj hasło.
        /// </summary>
        public static string PasswordTextBoxToolTip {
            get {
                return ResourceManager.GetString("PasswordTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj port w zakresie od 0 do 32 767.
        /// </summary>
        public static string PortTextBoxToolTip {
            get {
                return ResourceManager.GetString("PortTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwer uruchomiony.
        /// </summary>
        public static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz serwer.
        /// </summary>
        public static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymywanie serwera....
        /// </summary>
        public static string StoppingServer {
            get {
                return ResourceManager.GetString("StoppingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz serwer.
        /// </summary>
        public static string StopServer {
            get {
                return ResourceManager.GetString("StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz diagnostykę.
        /// </summary>
        public static string TurnOnLogging {
            get {
                return ResourceManager.GetString("TurnOnLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIEPRAWIDLOWE HASLO W KONFIGURACJI KLIENTA:.
        /// </summary>
        public static string WrongClientPassword {
            get {
                return ResourceManager.GetString("WrongClientPassword", resourceCulture);
            }
        }
    }
}
