//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App data directory:.
        /// </summary>
        public static string AppDataDirectory {
            get {
                return ResourceManager.GetString("AppDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string AppLang {
            get {
                return ResourceManager.GetString("AppLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot Server.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on server at Windows startup.
        /// </summary>
        public static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command:.
        /// </summary>
        public static string ClientCommand {
            get {
                return ResourceManager.GetString("ClientCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client connected:.
        /// </summary>
        public static string ClientConnected {
            get {
                return ResourceManager.GetString("ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client disconnected:.
        /// </summary>
        public static string ClientDisconnected {
            get {
                return ResourceManager.GetString("ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.ini FILE READ ERROR.
        /// </summary>
        public static string ConfigFileError {
            get {
                return ResourceManager.GetString("ConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection parameters:.
        /// </summary>
        public static string ConnectionParams {
            get {
                return ResourceManager.GetString("ConnectionParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string ConnectionPassword {
            get {
                return ResourceManager.GetString("ConnectionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string ConnectionPort {
            get {
                return ResourceManager.GetString("ConnectionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitAppTray {
            get {
                return ResourceManager.GetString("ExitAppTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement:.
        /// </summary>
        public static string Movement {
            get {
                return ResourceManager.GetString("Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password.
        /// </summary>
        public static string PasswordTextBoxToolTip {
            get {
                return ResourceManager.GetString("PasswordTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input port value in range between 0 to 32 767.
        /// </summary>
        public static string PortTextBoxToolTip {
            get {
                return ResourceManager.GetString("PortTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom aplikację ponownie w celu zmiany ustawień.
        /// </summary>
        public static string RestartAppLang {
            get {
                return ResourceManager.GetString("RestartAppLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart server to apply changes.
        /// </summary>
        public static string RestartServer {
            get {
                return ResourceManager.GetString("RestartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server started.
        /// </summary>
        public static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowWindowTray {
            get {
                return ResourceManager.GetString("ShowWindowTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on server.
        /// </summary>
        public static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start server.
        /// </summary>
        public static string StartServerTray {
            get {
                return ResourceManager.GetString("StartServerTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping server....
        /// </summary>
        public static string StoppingServer {
            get {
                return ResourceManager.GetString("StoppingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off server.
        /// </summary>
        public static string StopServer {
            get {
                return ResourceManager.GetString("StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop server.
        /// </summary>
        public static string StopServerTray {
            get {
                return ResourceManager.GetString("StopServerTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party licenses:.
        /// </summary>
        public static string ThirdPartyLicenses {
            get {
                return ResourceManager.GetString("ThirdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on logging.
        /// </summary>
        public static string TurnOnLogging {
            get {
                return ResourceManager.GetString("TurnOnLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received unknown command.
        /// </summary>
        public static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRONG CLIENT PASSWORD:.
        /// </summary>
        public static string WrongClientPassword {
            get {
                return ResourceManager.GetString("WrongClientPassword", resourceCulture);
            }
        }
    }
}
